baseurl = "http://hugo.test/"
languageCode = "en-us"
title = "Jack Whiting"

theme = "jackwhiting"
paginate = 10
pygmentsCodefences = true
pygmentsStyle = "native"



[permalinks]
    posts = "/posts/:slug/"
    works = "/works/:slug/"
    page = "/:slug/"